---
- hosts: digitalocean

  vars:
    do_token: <DigitalOcean API token>
    ssh_key_name: 'id_rsa'
  tasks:

  - name: ensure ssh key exists
    user: >
      name={{ ansible_user_id }}
      generate_ssh_key=yes
      ssh_key_file=.ssh/{{ssh_key_name}}
      state=present
    register: createdpath

  - name: ensure ssh key exists
    debug: msg="{{createdpath.ssh_key_file}}"

  - name: ensure key exists at DigitalOcean
    digital_ocean: >
      state=present
      command=ssh
      name=my_ssh_key
      ssh_pub_key={{ lookup('file', '~/.ssh/{{ssh_key_name}}.pub') }}
      api_token={{ do_token }}
    register: my_ssh_key

  - name: ensure droplet insta-go exists
    digital_ocean: >
      state=present
      command=droplet
      unique_name=yes
      name=insta-go
      size_id=512mb
      region_id=fra1
      image_id=ubuntu-16-04-x64
      ssh_key_ids={{ my_ssh_key.ssh_key.id }}
      api_token={{ do_token }}
    register: droplet_insta_go

  - debug: msg="IP is {{ droplet_insta_go.droplet.ip_address }}"
